#!/usr/bin/env python3
"""
axis_patcher.py — STAFF_PWA_V1_HOTFIX
=====================================

Why this hotfix exists
----------------------
The first pass of STAFF_PWA_V1 shipped a manifest that advertised
**SVG** icons only:

    /static/pwa/staff-icon-192.svg
    /static/pwa/staff-icon-512.svg

Chrome and Edge **do not consider a PWA installable** unless the
manifest also contains at least one **PNG** icon at 192x192 and one
at 512x512. SVG alone is silently ignored for installability. That
is why the staff "Install App" button falls back to the manual
instructions modal: `beforeinstallprompt` is never fired, so there
is no deferred prompt to call `.prompt()` on.

The admin panel works because it already serves PNGs from
`/static/pwa/icon-192x192.png` and `/static/pwa/icon-512x512.png`.

What this hotfix does
---------------------
1. Generates two **PNG** staff-portal icons entirely in Python
   (using only `zlib` + `struct` from the standard library — no
   Pillow, no external tools):

       static/pwa/staff-icon-192.png
       static/pwa/staff-icon-512.png

   The artwork is the AXIS Staff brand: teal gradient background,
   white monogram "A", gold accent bar underneath — rendered
   pixel-by-pixel with anti-aliased strokes.

2. Rewrites `axis_saas/views/staff_pwa.py` so the manifest and the
   service-worker pre-cache reference the PNG files. The file is
   only rewritten if it still carries our own marker string
   (`STAFF_PWA_V1`) — the patcher refuses to clobber anything it
   did not write.

3. Leaves `axis_saas/staff_urls.py` and
   `templates/mobile/staff/base.html` alone. The URL routes and the
   install-prompt JavaScript written by the first pass are already
   correct; only the manifest content and the icon assets needed
   to change.

Idempotency
-----------
The PNG writes are idempotent (skip when the file already exists).
The `staff_pwa.py` rewrite is idempotent because the replacement
content carries the same `STAFF_PWA_V1` marker — re-running this
patcher after a successful run is a no-op.

Usage
-----
    python axis_patcher.py --dry-run --verbose
    python axis_patcher.py
    python axis_patcher.py --target-dir /path/to/fee_management --verbose
"""

from __future__ import annotations

import argparse
import struct
import sys
import zlib
from datetime import datetime
from pathlib import Path


# ---------------------------------------------------------------------------
# Target paths (relative to project root)
# ---------------------------------------------------------------------------

STAFF_PWA_VIEW_REL = Path("axis_saas") / "views" / "staff_pwa.py"
ICON_192_REL       = Path("static") / "pwa" / "staff-icon-192.png"
ICON_512_REL       = Path("static") / "pwa" / "staff-icon-512.png"


# Marker string — every file this patcher owns must contain it so a
# future run can safely distinguish "our output" from "user's file".
MARKER = "STAFF_PWA_V1"


# ---------------------------------------------------------------------------
# New / updated file: axis_saas/views/staff_pwa.py
# ---------------------------------------------------------------------------
#
# Rewritten to advertise PNG icons in the manifest and to pre-cache
# the PNG files in the service worker. Everything else — the
# `start_url`, the `scope`, the network-first navigations, the
# cache-first static strategy — is unchanged from the first pass.

STAFF_PWA_VIEW_CONTENT = '''"""AXIS Staff Portal PWA — manifest + service worker.

STAFF_PWA_V1
------------
Adds PWA support to the staff portal, kept deliberately separate from
the school-admin PWA endpoints in ``axis_saas/pwa_views.py`` so the
two surfaces never interfere.

STAFF_PWA_V1_HOTFIX
-------------------
The first pass advertised SVG icons only. Chrome / Edge refuse to
fire ``beforeinstallprompt`` unless the manifest contains PNG icons
at 192x192 and 512x512, so the "Install App" button silently fell
through to the manual-instructions modal. The manifest now
advertises PNG icons generated by the patcher; the SVG files remain
in place as decorative favicons.

Key design notes
----------------
* Both endpoints are schema-independent. The staff portal is mounted
  at ``/portal/staff/`` (see ``axis_saas.staff_urls``) and resolves
  the tenant from the authenticated staff session, not from the URL.
  The manifest and service worker therefore live at stable paths:

      /portal/staff/manifest.json
      /portal/staff/sw.js

* The service worker scope is limited to ``/portal/staff/`` so it
  cannot control the school-admin pages or any other tenant surface.

* The service worker uses a *network-first* strategy for navigations
  (so staff always see fresh data when online, and can fall back to
  a cached copy when offline) and a *cache-first* strategy for static
  assets. API and auth endpoints are never cached.
"""
from django.http import HttpResponse, JsonResponse


def _manifest_icons():
    """Icon set for the staff PWA.

    PNG only. Chrome / Edge require at least one PNG icon of 192x192
    and one of 512x512 to consider the app installable. Both the
    "any" and "maskable" purposes point at the same artwork because
    the design already respects the maskable safe-zone (all content
    sits inside the center 80% circle).
    """
    return [
        {
            'src': '/static/pwa/staff-icon-192.png',
            'sizes': '192x192',
            'type': 'image/png',
            'purpose': 'any',
        },
        {
            'src': '/static/pwa/staff-icon-192.png',
            'sizes': '192x192',
            'type': 'image/png',
            'purpose': 'maskable',
        },
        {
            'src': '/static/pwa/staff-icon-512.png',
            'sizes': '512x512',
            'type': 'image/png',
            'purpose': 'any',
        },
        {
            'src': '/static/pwa/staff-icon-512.png',
            'sizes': '512x512',
            'type': 'image/png',
            'purpose': 'maskable',
        },
    ]


def staff_manifest(request):
    """Serve the staff-portal Web App Manifest.

    ``start_url`` points at the staff dashboard; ``scope`` is limited
    to ``/portal/staff/`` so installing the staff PWA never hijacks
    URLs outside the staff portal.
    """
    data = {
        'name': 'AXIS Staff Portal',
        'short_name': 'AXIS Staff',
        'description': (
            'AXIS staff portal — dashboard, classes, attendance, '
            'leave, profile.'
        ),
        'start_url': '/portal/staff/dashboard/',
        'scope': '/portal/staff/',
        'display': 'standalone',
        'orientation': 'portrait',
        'background_color': '#f2f7f6',
        'theme_color': '#0b6e64',
        'categories': ['education', 'productivity'],
        'lang': 'en',
        'icons': _manifest_icons(),
    }
    response = JsonResponse(data)
    response['Cache-Control'] = (
        'no-store, no-cache, must-revalidate, max-age=0'
    )
    return response


def staff_service_worker(request):
    """Serve the staff-portal service worker.

    Served from ``/portal/staff/sw.js`` so its default scope is
    ``/portal/staff/``. The ``Service-Worker-Allowed`` header is set
    defensively in case a proxy rewrites the path.
    """
    sw_js = r"""// AXIS Staff Portal Service Worker (STAFF_PWA_V1)
const CACHE_NAME = 'axis-staff-pwa-v1';
const PRECACHE_STATIC = [
    '/static/pwa/staff-icon-192.png',
    '/static/pwa/staff-icon-512.png',
];

self.addEventListener('install', function (event) {
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then(function (cache) {
                return cache.addAll(PRECACHE_STATIC).catch(function (err) {
                    console.warn('[AXIS Staff SW] pre-cache failed:', err);
                });
            })
            .then(function () { return self.skipWaiting(); })
    );
});

self.addEventListener('activate', function (event) {
    event.waitUntil(
        caches.keys().then(function (keys) {
            return Promise.all(keys.map(function (key) {
                if (key !== CACHE_NAME && key.indexOf('axis-staff-pwa-') === 0) {
                    return caches.delete(key);
                }
                return null;
            }));
        }).then(function () { return self.clients.claim(); })
    );
});

self.addEventListener('fetch', function (event) {
    var request = event.request;
    if (request.method !== 'GET' && request.method !== 'HEAD') {
        return;
    }
    var url;
    try {
        url = new URL(request.url);
    } catch (e) {
        return;
    }
    if (url.origin !== self.location.origin) {
        return;
    }

    // Never intercept API or auth traffic — the staff portal must
    // always reflect live server state for those.
    if (url.pathname.indexOf('/portal/staff/api/') !== -1
        || url.pathname.indexOf('/portal/staff/login') !== -1
        || url.pathname.indexOf('/portal/staff/logout') !== -1
        || url.pathname.indexOf('/portal/staff/biometric/') !== -1) {
        return;
    }

    // Network-first for page navigations, so staff see fresh data
    // when online, and a cached copy when offline.
    if (request.mode === 'navigate') {
        event.respondWith(
            fetch(request).catch(function () {
                return caches.match(request);
            })
        );
        return;
    }

    // Cache-first for everything else (static assets, stylesheets,
    // images). Cache successful same-origin GET responses.
    event.respondWith(
        caches.match(request).then(function (cached) {
            if (cached) {
                return cached;
            }
            return fetch(request).then(function (response) {
                if (response
                    && response.status === 200
                    && response.type === 'basic'
                    && url.pathname.indexOf('/portal/staff/') === 0) {
                    var clone = response.clone();
                    caches.open(CACHE_NAME).then(function (cache) {
                        cache.put(request, clone);
                    });
                }
                return response;
            });
        })
    );
});
"""
    response = HttpResponse(sw_js, content_type='application/javascript')
    response['Cache-Control'] = (
        'no-store, no-cache, must-revalidate, max-age=0'
    )
    response['Pragma'] = 'no-cache'
    response['Service-Worker-Allowed'] = '/portal/staff/'
    return response
'''


# ---------------------------------------------------------------------------
# Minimal pure-Python PNG encoder
# ---------------------------------------------------------------------------
#
# Chrome's installability check is strict: it wants real PNGs, not
# SVGs. Rather than adding Pillow as a runtime dependency, we encode
# the two icon sizes ourselves. The format is small enough to emit
# with zlib + struct.

def _png_chunk(chunk_type: bytes, data: bytes) -> bytes:
    """Assemble a single PNG chunk: length | type | data | crc32."""
    chunk = chunk_type + data
    return (
        struct.pack(">I", len(data))
        + chunk
        + struct.pack(">I", zlib.crc32(chunk) & 0xFFFFFFFF)
    )


def _make_png(width: int, height: int, pixel_fn) -> bytes:
    """Encode a full RGBA PNG from a per-pixel callback.

    ``pixel_fn(x, y)`` returns an ``(r, g, b, a)`` tuple of ints in
    the range 0..255. The encoder writes every pixel with filter
    type 0 (no prediction) which produces large intermediate buffers
    but compresses perfectly for smooth gradients and flat colours.
    """
    row_len = width * 4
    raw = bytearray((row_len + 1) * height)
    i = 0
    for y in range(height):
        raw[i] = 0  # PNG filter type 0 (None) for this scanline
        i += 1
        for x in range(width):
            r, g, b, a = pixel_fn(x, y)
            raw[i]     = r & 0xFF
            raw[i + 1] = g & 0xFF
            raw[i + 2] = b & 0xFF
            raw[i + 3] = a & 0xFF
            i += 4

    png = b"\x89PNG\r\n\x1a\n"
    # IHDR: width, height, bit-depth=8, colour-type=6 (RGBA),
    # compression=0, filter=0, interlace=0.
    png += _png_chunk(
        b"IHDR",
        struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0),
    )
    png += _png_chunk(b"IDAT", zlib.compress(bytes(raw), 9))
    png += _png_chunk(b"IEND", b"")
    return png


def _dist_to_segment(px: float, py: float,
                     x1: float, y1: float,
                     x2: float, y2: float) -> float:
    """Euclidean distance from point (px, py) to segment (x1,y1)-(x2,y2)."""
    dx = x2 - x1
    dy = y2 - y1
    denom = dx * dx + dy * dy
    if denom <= 0.0:
        return ((px - x1) ** 2 + (py - y1) ** 2) ** 0.5
    t = ((px - x1) * dx + (py - y1) * dy) / denom
    if t < 0.0:
        t = 0.0
    elif t > 1.0:
        t = 1.0
    nx = x1 + t * dx
    ny = y1 + t * dy
    return ((px - nx) ** 2 + (py - ny) ** 2) ** 0.5


def _staff_icon_pixel_fn(size: int):
    """Return a pixel callback rendering the AXIS Staff icon.

    The design:
      * Full-bleed teal gradient background (135° diagonal).
      * A bold white "A" monogram built from three anti-aliased
        strokes (two legs meeting at an apex, plus a crossbar).
      * A gold gradient accent bar sitting underneath the monogram.

    All proportions are expressed as fractions of ``size`` so the
    192 and 512 variants are visually identical.
    """
    s = float(size)

    # A monogram geometry (fractions of size)
    a_apex_x, a_apex_y = 0.500, 0.240
    a_left_x, a_left_y = 0.320, 0.720
    a_right_x, a_right_y = 0.680, 0.720
    cb_y = 0.560
    cb_x0, cb_x1 = 0.380, 0.620
    stroke_half = 0.040 * s          # half-thickness of the strokes

    # Gold accent bar (fractions of size)
    bar_x0 = 0.360
    bar_x1 = 0.640
    bar_y0 = 0.790
    bar_y1 = 0.825

    # Pre-resolve pixel coordinates for the segment endpoints
    ax_l, ay_l = a_left_x * s,  a_left_y * s
    ax_r, ay_r = a_right_x * s, a_right_y * s
    ax_a, ay_a = a_apex_x * s,  a_apex_y * s
    cbx0, cbx1 = cb_x0 * s, cb_x1 * s
    cby        = cb_y * s
    barx0 = int(bar_x0 * s)
    barx1 = int(bar_x1 * s)
    bary0 = int(bar_y0 * s)
    bary1 = int(bar_y1 * s)

    def pixel(x, y):
        nx = x / s
        ny = y / s

        # ---- teal gradient background (135° diagonal) ----
        t = (nx + ny) * 0.5
        if t < 0.55:
            u = t / 0.55
            r = int(0x14 + (0x0b - 0x14) * u + 0.5)
            g = int(0xc2 + (0x6e - 0xc2) * u + 0.5)
            b = int(0xb0 + (0x64 - 0xb0) * u + 0.5)
        else:
            u = (t - 0.55) / 0.45
            r = int(0x0b + (0x06 - 0x0b) * u + 0.5)
            g = int(0x6e + (0x3a - 0x6e) * u + 0.5)
            b = int(0x64 + (0x36 - 0x64) * u + 0.5)

        # ---- white "A" monogram (anti-aliased) ----
        d_left = _dist_to_segment(x, y, ax_l, ay_l, ax_a, ay_a)
        d_right = _dist_to_segment(x, y, ax_r, ay_r, ax_a, ay_a)
        d_cross = _dist_to_segment(x, y, cbx0, cby, cbx1, cby)
        d_min = min(d_left, d_right, d_cross)

        if d_min < stroke_half:
            edge = stroke_half - d_min
            if edge >= 1.5:
                r, g, b = 255, 255, 255
            else:
                a_blend = edge / 1.5
                r = int(r * (1.0 - a_blend) + 255 * a_blend + 0.5)
                g = int(g * (1.0 - a_blend) + 255 * a_blend + 0.5)
                b = int(b * (1.0 - a_blend) + 255 * a_blend + 0.5)

        # ---- gold accent bar (draw last so it sits on top) ----
        if bary0 <= y < bary1 and barx0 <= x < barx1:
            span = barx1 - barx0
            u = (x - barx0) / span if span > 0 else 0.0
            r = int(0xc9 + (0xf0 - 0xc9) * u + 0.5)
            g = int(0xa2 + (0xd8 - 0xa2) * u + 0.5)
            b = int(0x27 + (0x76 - 0x27) * u + 0.5)

        return (r, g, b, 255)

    return pixel


def _staff_icon_png(size: int) -> bytes:
    """Render the AXIS Staff icon at ``size`` x ``size`` and return PNG bytes."""
    return _make_png(size, size, _staff_icon_pixel_fn(size))


# ---------------------------------------------------------------------------
# Logging helpers
# ---------------------------------------------------------------------------

def ts() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


class Log:
    def __init__(self, verbose: bool) -> None:
        self.verbose = verbose

    def info(self, message: str) -> None:
        print(f"[{ts()}] {message}")

    def detail(self, message: str) -> None:
        if self.verbose:
            print(f"[{ts()}]   -> {message}")

    def error(self, message: str) -> None:
        print(f"[{ts()}] ERROR: {message}", file=sys.stderr)


# ---------------------------------------------------------------------------
# File-operation helpers
# ---------------------------------------------------------------------------

def write_binary_file(
    target: Path,
    content: bytes,
    log: Log,
    dry_run: bool,
) -> int:
    """Create a new binary file. Idempotent: skip if it already exists."""
    if target.exists():
        log.info(f"{target.name}: already present (idempotent no-op)")
        return 0

    try:
        target.parent.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        log.error(f"could not create parent dir for {target}: {exc}")
        return 1

    if dry_run:
        log.info(f"{target}: would create ({len(content)} bytes)")
        return 0

    try:
        target.write_bytes(content)
    except OSError as exc:
        log.error(f"failed to write {target}: {exc}")
        return 1

    log.info(f"{target}: created ({len(content)} bytes)")
    return 0


def rewrite_if_mine(
    target: Path,
    content: str,
    marker: str,
    log: Log,
    dry_run: bool,
) -> int:
    """Create-or-replace a file that this patcher owns.

    The contract:
      * Target does not exist           → create it.
      * Target exists, contains marker  → replace it (this is our file,
                                          a previous pass wrote it, and
                                          this hotfix is updating it).
      * Target exists, no marker        → refuse (do not clobber a file
                                          the user or another tool wrote).
    """
    if target.exists():
        try:
            existing = target.read_text(encoding="utf-8")
        except OSError as exc:
            log.error(f"could not read existing file {target}: {exc}")
            return 1

        if marker in existing:
            if existing == content:
                log.info(
                    f"{target.name}: content already up to date "
                    f"(idempotent no-op)"
                )
                return 0
            log.info(
                f"{target.name}: ours, replacing with updated content "
                f"({len(existing)} -> {len(content)} bytes)"
            )
            if dry_run:
                log.detail(f"would overwrite: {target}")
                return 0
            try:
                target.write_text(content, encoding="utf-8")
            except OSError as exc:
                log.error(f"failed to write {target}: {exc}")
                return 1
            log.info(f"{target.name}: rewritten")
            return 0

        log.error(
            f"{target} exists but does not contain the expected marker "
            f"{marker!r}. Refusing to overwrite — this file appears to "
            f"be user-owned or produced by a different tool."
        )
        return 1

    try:
        target.parent.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        log.error(f"could not create parent dir for {target}: {exc}")
        return 1

    if dry_run:
        log.info(f"{target}: would create ({len(content)} bytes)")
        return 0

    try:
        target.write_text(content, encoding="utf-8")
    except OSError as exc:
        log.error(f"failed to write {target}: {exc}")
        return 1

    log.info(f"{target}: created ({len(content)} bytes)")
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "STAFF_PWA_V1_HOTFIX — fix the staff-portal PWA manifest so "
            "Chrome/Edge fire `beforeinstallprompt` (requires PNG icons, "
            "not SVG)."
        ),
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Preview changes without writing to disk.",
    )
    parser.add_argument(
        "--verbose", action="store_true",
        help="Show detailed output for every action.",
    )
    parser.add_argument(
        "--target-dir", default=".",
        help="Project root (default: current directory).",
    )
    return parser


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    log = Log(args.verbose)

    try:
        root = Path(args.target_dir).expanduser().resolve()
    except OSError as exc:
        print(f"[{ts()}] ERROR: cannot resolve target dir: {exc}",
              file=sys.stderr)
        return 1

    log.info(f"target root : {root}")
    if args.dry_run:
        log.info("mode        : DRY RUN (no files will be written)")
    log.info("patcher     : STAFF_PWA_V1_HOTFIX")
    log.info("")

    if not root.exists() or not root.is_dir():
        log.error(
            f"target directory does not exist or is not a directory: {root}"
        )
        return 1

    rc = 0

    # --- PNG icons --------------------------------------------------------
    # Rendered at runtime; the encoder is pure stdlib.
    log.info("")
    log.info(f"--- {ICON_192_REL} ---")
    try:
        icon_192_bytes = _staff_icon_png(192)
    except Exception as exc:
        log.error(f"could not render 192px staff icon: {exc}")
        return 1
    rc |= write_binary_file(
        root / ICON_192_REL,
        icon_192_bytes,
        log=log,
        dry_run=args.dry_run,
    )

    log.info("")
    log.info(f"--- {ICON_512_REL} ---")
    try:
        icon_512_bytes = _staff_icon_png(512)
    except Exception as exc:
        log.error(f"could not render 512px staff icon: {exc}")
        return 1
    rc |= write_binary_file(
        root / ICON_512_REL,
        icon_512_bytes,
        log=log,
        dry_run=args.dry_run,
    )

    # --- staff_pwa.py: manifest + SW now point at the PNGs ----------------
    log.info("")
    log.info(f"--- {STAFF_PWA_VIEW_REL} ---")
    rc |= rewrite_if_mine(
        root / STAFF_PWA_VIEW_REL,
        STAFF_PWA_VIEW_CONTENT,
        marker=MARKER,
        log=log,
        dry_run=args.dry_run,
    )

    log.info("")
    if args.dry_run:
        log.info("dry run complete - no changes were written")
    elif rc == 0:
        log.info("done.")
    else:
        log.info("done with errors - see above.")

    return rc


if __name__ == "__main__":
    sys.exit(main())
