# Generated by Django 4.2.16 on 2026-09-02 09:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("due_date", models.DateField()),
                (
                    "due_date_offset",
                    models.PositiveSmallIntegerField(
                        default=15, help_text="Days after generation when fee is due"
                    ),
                ),
                (
                    "late_fee_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Late fee amount applied per day",
                        max_digits=6,
                    ),
                ),
                (
                    "late_fee_accrued",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Accrued late fee amount for overdue days",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partial", "Partially Paid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("waived", "Waived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "extra_charges",
                    models.JSONField(blank=True, default=list, null=True),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField(max_length=50, unique=True)),
                (
                    "monthly_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ManualGenerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("skipped_existing", models.PositiveIntegerField(default=0)),
                ("skipped_no_fee", models.PositiveIntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "triggered_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[("manual", "Manual"), ("auto", "Auto")],
                        default="manual",
                        help_text="Type of generation (manual or auto)",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("link", models.CharField(blank=True, max_length=255, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Product Categories",
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Class name, e.g., 'Grade 5'", max_length=100
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True, help_text="Section, e.g., 'A'", max_length=10
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "section"],
            },
        ),
        migrations.CreateModel(
            name="SchoolClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_on", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "admin_username",
                    models.CharField(default="admin_pending", max_length=150),
                ),
                (
                    "admin_password",
                    models.CharField(default="AxisFallback123!", max_length=128),
                ),
                (
                    "school_logo",
                    models.FileField(blank=True, null=True, upload_to="school_logos/"),
                ),
                (
                    "tenant_type",
                    models.CharField(
                        choices=[("school", "School")], default="school", max_length=20
                    ),
                ),
                (
                    "enabled_features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Select the school modules enabled for this tenant.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SchoolFeeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fee_generation_day",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Day of month (1-31)"
                    ),
                ),
                (
                    "due_date_offset",
                    models.PositiveSmallIntegerField(
                        default=15, help_text="Days after generation when fee is due"
                    ),
                ),
                (
                    "late_fee_penalty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Penalty %",
                        max_digits=5,
                    ),
                ),
                (
                    "default_extra_charges",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Common charges used for future vouchers",
                        null=True,
                    ),
                ),
                (
                    "automation_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable monthly auto‑generation of fees",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Fee Settings",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_id", models.CharField(blank=True, max_length=20, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("full_name", models.CharField(blank=True, max_length=200)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("cnic", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("job_title", models.CharField(max_length=100)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("admin", "Administration"),
                            ("teaching", "Teaching"),
                            ("support", "Support Staff"),
                            ("other", "Other"),
                        ],
                        default="teaching",
                        max_length=50,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("teacher", "Teacher"),
                            ("class_teacher", "Class Teacher"),
                            ("subject_teacher", "Subject Teacher"),
                            ("admin", "Admin"),
                        ],
                        default="teacher",
                        max_length=30,
                    ),
                ),
                ("can_mark_attendance", models.BooleanField(default=True)),
                ("can_view_fees", models.BooleanField(default=False)),
                ("hire_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="staff_photos/"),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="StaffCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "visible_password",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("staff_id", models.PositiveIntegerField()),
                ("schema_name", models.CharField(max_length=63)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("failed_attempts", models.PositiveIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["username"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=150)),
                ("father_name", models.CharField(db_index=True, max_length=150)),
                (
                    "father_cnic",
                    models.CharField(
                        db_index=True, help_text="35202-XXXXXXX-X", max_length=15
                    ),
                ),
                ("parent_mobile", models.CharField(db_index=True, max_length=15)),
                ("grade", models.CharField(db_index=True, max_length=50)),
                ("section", models.CharField(db_index=True, max_length=50)),
                ("admission_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("graduated", "Graduated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_photos/"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "roll_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, unique=True
                    ),
                ),
                (
                    "custom_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("enrolled_on", models.DateTimeField(auto_now_add=True)),
                (
                    "default_extra_charges",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "automation_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable monthly auto‑generation of fees",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="axis_saas.schoolclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="axis_saas.schoolclient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_teacher_of",
                to="axis_saas.staff",
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("sku", models.CharField(blank=True, max_length=50, unique=True)),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="axis_saas.productcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateField(auto_now_add=True)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("online", "Online"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("payment_type", models.CharField(default="full", max_length=20)),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, unique=True
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "extra_charges",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=150)),
                (
                    "fee_records",
                    models.ManyToManyField(
                        related_name="payments", to="axis_saas.feerecord"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="axis_saas.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feerecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_records",
                to="axis_saas.student",
            ),
        ),
        migrations.CreateModel(
            name="ClassSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True, help_text="e.g., 2024-2025", max_length=20
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_subjects",
                        to="axis_saas.schoolclass",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_subjects",
                        to="axis_saas.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"status": "active"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_subjects",
                        to="axis_saas.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["school_class", "subject"],
            },
        ),
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("holiday", "Holiday"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="axis_saas.schoolclass",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="axis_saas.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_attendance",
                        to="axis_saas.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "student__name"],
                "indexes": [
                    models.Index(
                        fields=["school_class", "date"],
                        name="axis_saas_s_school__9ce8de_idx",
                    )
                ],
                "unique_together": {("student", "date")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="schoolclass",
            unique_together={("name", "section")},
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_items",
                        to="axis_saas.paymenttransaction",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_items",
                        to="axis_saas.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["payment", "product"],
                        name="axis_saas_s_payment_bac01d_idx",
                    ),
                    models.Index(
                        fields=["product", "created_at"],
                        name="axis_saas_s_product_92f579_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["student", "payment_date"],
                name="axis_saas_p_student_433aa0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["payment_date"], name="axis_saas_p_payment_aae0e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feerecord",
            index=models.Index(
                fields=["student", "month", "year"],
                name="axis_saas_f_student_fa5b94_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feerecord",
            index=models.Index(
                fields=["status", "due_date"], name="axis_saas_f_status_c02e1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feerecord",
            index=models.Index(
                fields=["year", "month"], name="axis_saas_f_year_097ad6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feerecord",
            unique_together={("student", "month", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="classsubject",
            unique_together={("school_class", "subject")},
        ),
    ]
