# Generated by Django 4.2.16 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0002_repair_missing_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffBiometricCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.PositiveIntegerField(db_index=True)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('credential_id', models.TextField(unique=True)),
                ('public_key', models.TextField(blank=True, default='')),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('staff_id', 'schema_name', 'credential_id')},
            },
        ),
    ]
