# Generated by Django 4.2.16 on 2026-09-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("axis_saas", "0005_alter_schoolclient_tenant_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolclient",
            name="tenant_type",
            field=models.CharField(
                choices=[
                    ("wing_school", "Wing School"),
                    ("single_small_school", "Single Small School"),
                ],
                default="wing_school",
                max_length=30,
            ),
        ),
    ]
