# Generated by Django 4.2.16 on 2026-09-05 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("axis_saas", "0006_alter_schoolclient_tenant_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="WingCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["parent__name", "name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="schoolclass",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.UniqueConstraint(
                fields=("wing_category", "name", "section"),
                name="unique_class_per_wing_category",
            ),
        ),
        migrations.AddField(
            model_name="wingcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="axis_saas.wingcategory",
            ),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="wing_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes",
                to="axis_saas.wingcategory",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="wing_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="axis_saas.wingcategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="wingcategory",
            constraint=models.UniqueConstraint(
                fields=("parent", "name"), name="unique_wing_category_name"
            ),
        ),
    ]
