# Generated by axis_patcher.py
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('axis_saas', '0007_wingcategory_alter_schoolclass_unique_together_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE axis_saas_staff DROP COLUMN IF EXISTS father_name;",
            reverse_sql="ALTER TABLE axis_saas_staff ADD COLUMN father_name varchar(150) NOT NULL DEFAULT '';"
        ),
    ]
