# Generated by Django 4.2.16 on 2026-09-09 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0008_drop_staff_father_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.JSONField(default=list, help_text='List of integers 0-6 (Monday=0 to Sunday=6) representing working days.')),
                ('school_start_time', models.TimeField(default='08:00:00')),
                ('school_end_time', models.TimeField(default='14:00:00')),
                ('period_duration', models.PositiveIntegerField(default=45, help_text='Duration in minutes for each period.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Academic Calendars',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('is_recurring', models.BooleanField(default=False, help_text='If true, this holiday repeats every year.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Order of the period in the day (1, 2, 3, ...).')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('name', models.CharField(blank=True, help_text="Optional name, e.g., 'Period 1'", max_length=50)),
                ('academic_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='axis_saas.academiccalendar')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('academic_calendar', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('academic_year', models.CharField(blank=True, help_text='e.g., 2024-2025', max_length=20)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='axis_saas.period')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='axis_saas.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='axis_saas.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='axis_saas.staff')),
            ],
            options={
                'indexes': [models.Index(fields=['school_class', 'day_of_week'], name='axis_saas_t_school__0204b1_idx'), models.Index(fields=['teacher', 'day_of_week', 'period'], name='axis_saas_t_teacher_b86fbe_idx')],
                'unique_together': {('school_class', 'day_of_week', 'period')},
            },
        ),
    ]
