# Generated by Django 4.2.16 on 2026-09-09 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0009_academiccalendar_holiday_period_timetableentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(default='08:00:00')),
                ('end_time', models.TimeField(default='14:00:00')),
                ('periods', models.PositiveIntegerField(default=8, help_text='Number of periods on this day.')),
                ('duration', models.PositiveIntegerField(default=45, help_text='Duration per period in minutes.')),
                ('is_active', models.BooleanField(default=True)),
                ('academic_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_schedules', to='axis_saas.academiccalendar')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('academic_calendar', 'day_of_week')},
            },
        ),
    ]
