# Generated by axis_patcher_fix_migration.py
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0010_dayschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayschedule',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of this slot within the day'),
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Optional label, e.g., Senior, Junior', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='dayschedule',
            unique_together=set(),
        ),
    ]
