# Generated by axis_patcher_label_required.py
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0011_alter_dayschedule_add_order_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayschedule',
            name='label',
            field=models.CharField(default='', help_text='Optional label, e.g., Senior, Junior', max_length=50),
        ),
    ]
