# Generated by axis_patcher_periods.py
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0013_vacation_weeklyholiday_alter_dayschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayschedule',
            name='break_after',
            field=models.PositiveIntegerField(blank=True, help_text='After which period (1-indexed) the break occurs.', null=True),
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='break_duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration of break in minutes.'),
        ),
    ]
