# Generated by Django 4.2.16 on 2026-09-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0015_schedulelabel'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dayschedule',
            constraint=models.UniqueConstraint(fields=('academic_calendar', 'label', 'day_of_week'), name='unique_label_per_day'),
        ),
    ]
