# Generated by axis_patcher — Timetable Assignments feature.
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0016_dayschedule_unique_label_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodsTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('label', models.CharField(blank=True, default='', max_length=50)),
                ('break_duration', models.PositiveIntegerField(default=0)),
                ('days', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'Periods Timetable',
                'verbose_name_plural': 'Periods Timetables',
            },
        ),
        migrations.CreateModel(
            name='ClassTimetableAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='timetable_assignment',
                    to='axis_saas.schoolclass',
                )),
                ('timetable', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='class_assignments',
                    to='axis_saas.periodstimetable',
                )),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
