# Generated by axis_patcher — Assign-to-Teachers feature.
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0017_periods_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('period_order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='period_teacher_assignments',
                    to='axis_saas.schoolclass',
                )),
                ('subject', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='period_teacher_assignments',
                    to='axis_saas.subject',
                )),
                ('teacher', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='period_teacher_assignments',
                    to='axis_saas.staff',
                )),
            ],
            options={
                'ordering': ['school_class', 'day_of_week', 'period_order'],
                'unique_together': {('school_class', 'day_of_week', 'period_order')},
            },
        ),
    ]
