# Generated by axis_patcher — TIMETABLE_SAVE_V3_MIGRATION
#
# Replaces the case-sensitive unique constraint on
# (academic_calendar, label, day_of_week) with a case-insensitive one.
#
# Safety:
#   1. First deletes any pre-existing case-variant duplicates
#      (e.g. both "Senior" and "senior" on the same day in the same
#      calendar), keeping the row with the lowest id.
#   2. Then drops the old constraint *only if it exists*. Some schemas
#      may not have it if 0016 was skipped by fix_missing_tables.
#   3. Finally adds the new case-insensitive constraint.
#
# PostgreSQL DDL is transactional, so if any step fails the whole
# migration rolls back cleanly.
#
from django.db import migrations, models
from django.db.models.functions import Lower


def dedupe_dayschedule(apps, schema_editor):
    """Delete duplicate (academic_calendar_id, LOWER(label), day_of_week)
    rows, keeping the row with the lowest id in each group.

    This MUST run before the CI unique constraint is added; otherwise the
    AddConstraint operation fails on tenants that already contain
    case-variant duplicates like "Senior" and "senior" on the same day.
    """
    schema_editor.execute(
        "DELETE FROM axis_saas_dayschedule "
        "WHERE id NOT IN ("
        "  SELECT MIN(id) FROM axis_saas_dayschedule "
        "  GROUP BY academic_calendar_id, LOWER(label), day_of_week"
        ");"
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0018_period_teacher_assignment'),
    ]

    operations = [
        # 1) Clean pre-existing case-variant duplicates FIRST.
        migrations.RunPython(dedupe_dayschedule, noop),

        # 2) Drop the old constraint if it exists (idempotent).
        #    We use SeparateDatabaseAndState so the state tracker removes
        #    the constraint while the DB command is IF EXISTS — this keeps
        #    the migration safe to apply on tenants whose history is
        #    incomplete.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE axis_saas_dayschedule "
                        "DROP CONSTRAINT IF EXISTS unique_label_per_day;"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='dayschedule',
                    name='unique_label_per_day',
                ),
            ],
        ),

        # 3) Add the new case-insensitive unique constraint.
        migrations.AddConstraint(
            model_name='dayschedule',
            constraint=models.UniqueConstraint(
                Lower('label'),
                'academic_calendar',
                'day_of_week',
                name='unique_label_per_day_ci',
            ),
        ),
    ]
