# Generated by axis_patcher — TIMETABLE_OPTIMISTIC_LOCK_V1
#
# Adds DaySchedule.updated_at so the calendar save endpoint can refuse to
# overwrite rows that someone else changed between page load and save.
#
# null=True is intentional: existing rows (before this migration) get
# NULL, which the save endpoint treats as "no version info — allow
# overwrite". New rows and any subsequent save will populate it.
#
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0019_dayschedule_ci_label_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, blank=True),
        ),
    ]
