# Generated by g3.py — TIMETABLE_FK_REFACTOR_V1_RECOVERY
#
# Three-step FK refactor, step 1 of 3.
#
# This migration is IDEMPOTENT against every partial DB state a prior
# aborted run could have left behind. It:
#
#   1. Deletes case-variant ScheduleLabel duplicates.
#   2. Normalizes the two timetable tables: drops a stray `label_id`
#      column if present, and renames `label_legacy` back to `label`
#      so the standard operations below apply cleanly.
#   3. Drops the CI unique constraint on DaySchedule (idempotent).
#   4. Renames the CharField `label` on both models to `label_legacy`.
#   5. Adds a NULLABLE FK `label` -> ScheduleLabel on both models.
#   6. Adds a CI unique index to ScheduleLabel.name.
#
# Every DDL statement uses IF EXISTS / IF NOT EXISTS and every Django
# operation is wrapped in SeparateDatabaseAndState so the migration can
# be re-run any number of times without erroring.

from django.db import migrations, models
import django.db.models.deletion
from django.db.models.functions import Lower


def dedupe_schedule_labels(apps, schema_editor):
    """Delete case-variant duplicates in ScheduleLabel, keeping the
    lowest-id row of each .lower() group."""
    ScheduleLabel = apps.get_model("axis_saas", "ScheduleLabel")
    seen = {}
    delete_ids = []
    for row in ScheduleLabel.objects.order_by("id"):
        key = (row.name or "").strip().lower()
        if not key:
            continue
        if key in seen:
            delete_ids.append(row.id)
        else:
            seen[key] = row.id
    if delete_ids:
        ScheduleLabel.objects.filter(id__in=delete_ids).delete()


def normalize_partial_state(apps, schema_editor):
    """Ensure axis_saas_dayschedule and axis_saas_periodstimetable are in
    the pre-0021 shape (label CharField present, no label_legacy, no
    label_id) even if a prior run aborted mid-refactor.

    A prior run of this migration can leave any of these combinations:

        * label      only  -> clean pre-0021.  No-op.
        * label + label_id -> partial.  Drop label_id.
        * label_legacy only -> partial rename.  Rename back to label.
        * label + label_legacy -> very odd.  Drop label_legacy.
        * label_legacy + label_id -> partial rename + partial FK add.
          Rename back to label, drop label_id.

    After this function returns, both tables have `label` (CharField) and
    no `label_legacy`, no `label_id`.
    """
    cursor = schema_editor.connection.cursor()

    for table in ('axis_saas_dayschedule', 'axis_saas_periodstimetable'):
        # 1) Drop the FK column if a partial run added it.
        cursor.execute(f'ALTER TABLE {table} DROP COLUMN IF EXISTS label_id')

        # 2) Ensure `label` exists.
        cursor.execute(
            "SELECT 1 FROM information_schema.columns "
            "WHERE table_schema = current_schema() "
            "  AND table_name = %s "
            "  AND column_name = 'label'",
            [table],
        )
        has_label = cursor.fetchone() is not None

        cursor.execute(
            "SELECT 1 FROM information_schema.columns "
            "WHERE table_schema = current_schema() "
            "  AND table_name = %s "
            "  AND column_name = 'label_legacy'",
            [table],
        )
        has_legacy = cursor.fetchone() is not None

        if has_label and has_legacy:
            # Very odd.  Keep `label`, drop `label_legacy`.
            cursor.execute(f'ALTER TABLE {table} DROP COLUMN IF EXISTS label_legacy')
        elif not has_label and has_legacy:
            # Partial rename.  Put it back.
            cursor.execute(
                f'ALTER TABLE {table} RENAME COLUMN label_legacy TO label'
            )
        elif not has_label and not has_legacy:
            raise RuntimeError(
                f"Neither 'label' nor 'label_legacy' exists on {table}. "
                f"Cannot normalise DB state for the 0021 FK refactor. "
                f"Restore from backup or inspect the schema manually."
            )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("axis_saas", "0020_dayschedule_optimistic_lock"),
    ]

    operations = [
        migrations.RunPython(dedupe_schedule_labels, noop),
        migrations.RunPython(normalize_partial_state, noop),

        # --- 1) Drop the CI unique constraint on DaySchedule --------------
        # Wrapped in SeparateDatabaseAndState: the DB operation uses
        # DROP CONSTRAINT IF EXISTS so it is safe to re-run, while the
        # state operation removes the constraint from the model state.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE axis_saas_dayschedule "
                    "DROP CONSTRAINT IF EXISTS unique_label_per_day_ci;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="dayschedule",
                    name="unique_label_per_day_ci",
                ),
            ],
        ),

        # --- 2) Rename label -> label_legacy on DaySchedule --------------
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE axis_saas_dayschedule "
                    "RENAME COLUMN label TO label_legacy;",
                    reverse_sql=(
                        "ALTER TABLE axis_saas_dayschedule "
                        "RENAME COLUMN label_legacy TO label;"
                    ),
                ),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name="dayschedule",
                    old_name="label",
                    new_name="label_legacy",
                ),
            ],
        ),

        # --- 3) Rename label -> label_legacy on PeriodsTimetable ---------
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE axis_saas_periodstimetable "
                    "RENAME COLUMN label TO label_legacy;",
                    reverse_sql=(
                        "ALTER TABLE axis_saas_periodstimetable "
                        "RENAME COLUMN label_legacy TO label;"
                    ),
                ),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name="periodstimetable",
                    old_name="label",
                    new_name="label_legacy",
                ),
            ],
        ),

        # --- 4) Add the new FK on DaySchedule (nullable, idempotent) -----
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE axis_saas_dayschedule "
                    "ADD COLUMN IF NOT EXISTS label_id bigint NULL "
                    "REFERENCES axis_saas_schedulelabel(id) "
                    "ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;",
                    reverse_sql=(
                        "ALTER TABLE axis_saas_dayschedule "
                        "DROP COLUMN IF EXISTS label_id;"
                    ),
                ),
                migrations.RunSQL(
                    "CREATE INDEX IF NOT EXISTS axis_saas_daysche_label_id_idx "
                    "ON axis_saas_dayschedule (label_id);",
                    reverse_sql=(
                        "DROP INDEX IF EXISTS axis_saas_daysche_label_id_idx;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="dayschedule",
                    name="label",
                    field=models.ForeignKey(
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="day_schedules",
                        to="axis_saas.schedulelabel",
                    ),
                ),
            ],
        ),

        # --- 5) Add the new FK on PeriodsTimetable (nullable, idempotent)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE axis_saas_periodstimetable "
                    "ADD COLUMN IF NOT EXISTS label_id bigint NULL "
                    "REFERENCES axis_saas_schedulelabel(id) "
                    "ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;",
                    reverse_sql=(
                        "ALTER TABLE axis_saas_periodstimetable "
                        "DROP COLUMN IF EXISTS label_id;"
                    ),
                ),
                migrations.RunSQL(
                    "CREATE INDEX IF NOT EXISTS axis_saas_ptt_label_id_idx "
                    "ON axis_saas_periodstimetable (label_id);",
                    reverse_sql=(
                        "DROP INDEX IF EXISTS axis_saas_ptt_label_id_idx;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="periodstimetable",
                    name="label",
                    field=models.ForeignKey(
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="periods_timetables",
                        to="axis_saas.schedulelabel",
                    ),
                ),
            ],
        ),

        # --- 6) CI unique index on ScheduleLabel.name --------------------
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "CREATE UNIQUE INDEX IF NOT EXISTS "
                    "unique_schedulelabel_name_ci "
                    "ON axis_saas_schedulelabel (LOWER(name));",
                    reverse_sql=(
                        "DROP INDEX IF EXISTS unique_schedulelabel_name_ci;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="schedulelabel",
                    constraint=models.UniqueConstraint(
                        Lower("name"),
                        name="unique_schedulelabel_name_ci",
                    ),
                ),
            ],
        ),
    ]
