# Generated by axis_patcher — TIMETABLE_FK_REFACTOR_V1 (step 2/3)
#
# Populate the new `label` FK on DaySchedule and PeriodsTimetable from
# the deprecated `label_legacy` CharField. Missing ScheduleLabels are
# created on the fly so no slot loses its label text in the process.

from django.db import migrations
from django.db.models.functions import Lower


def populate_fks(apps, schema_editor):
    ScheduleLabel = apps.get_model("axis_saas", "ScheduleLabel")
    DaySchedule = apps.get_model("axis_saas", "DaySchedule")
    PeriodsTimetable = apps.get_model("axis_saas", "PeriodsTimetable")

    canonical = {}
    for row in ScheduleLabel.objects.all():
        key = (row.name or "").strip().lower()
        if key:
            canonical[key] = row.id

    texts = set()
    for t in DaySchedule.objects.values_list("label_legacy", flat=True):
        if t and t.strip():
            texts.add(t.strip())
    for t in PeriodsTimetable.objects.values_list("label_legacy", flat=True):
        if t and t.strip():
            texts.add(t.strip())

    for text in texts:
        key = text.lower()
        if key not in canonical:
            # Truncate defensively; ScheduleLabel.name is max_length=50.
            new_lbl = ScheduleLabel.objects.create(name=text[:50], description="")
            canonical[key] = new_lbl.id

    # Rows with a blank label_legacy cannot be FK-linked. Delete them;
    # they were invalid under the old CI unique constraint anyway.
    DaySchedule.objects.filter(label_legacy="").delete()
    DaySchedule.objects.filter(label_legacy__isnull=True).delete()
    PeriodsTimetable.objects.filter(label_legacy="").delete()
    PeriodsTimetable.objects.filter(label_legacy__isnull=True).delete()

    for ds in DaySchedule.objects.all().only("id", "label_legacy"):
        key = (ds.label_legacy or "").strip().lower()
        lid = canonical.get(key)
        if lid:
            DaySchedule.objects.filter(pk=ds.pk).update(label_id=lid)

    for tt in PeriodsTimetable.objects.all().only("id", "label_legacy"):
        key = (tt.label_legacy or "").strip().lower()
        lid = canonical.get(key)
        if lid:
            PeriodsTimetable.objects.filter(pk=tt.pk).update(label_id=lid)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("axis_saas", "0021_schedulelabel_fk_step1"),
    ]

    operations = [
        migrations.RunPython(populate_fks, noop),
    ]
