# Generated by axis_patcher — TIMETABLE_FK_REFACTOR_V1 (step 3/3)
#
# Tighten the new FK column: drop the now-unused label_legacy
# CharFields, make the FK non-nullable, and install the natural
# unique constraint (label, academic_calendar, day_of_week) that
# replaces the functional Lower('label') index dropped in 0021.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("axis_saas", "0022_schedulelabel_fk_step2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dayschedule",
            name="label_legacy",
        ),
        migrations.RemoveField(
            model_name="periodstimetable",
            name="label_legacy",
        ),

        migrations.AlterField(
            model_name="dayschedule",
            name="label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="day_schedules",
                to="axis_saas.schedulelabel",
                help_text="The ScheduleLabel this slot belongs to.",
            ),
        ),
        migrations.AlterField(
            model_name="periodstimetable",
            name="label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="periods_timetables",
                to="axis_saas.schedulelabel",
            ),
        ),

        migrations.AddConstraint(
            model_name="dayschedule",
            constraint=models.UniqueConstraint(
                fields=("label", "academic_calendar", "day_of_week"),
                name="unique_label_per_day",
            ),
        ),
    ]
