# Generated by axis_patcher - LEAVE_MANAGEMENT_V1
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0023_schedulelabel_fk_step3'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_leaves_per_month', models.PositiveIntegerField(default=4, help_text='Maximum leave days a staff member can take in a calendar month.')),
                ('max_leaves_per_week', models.PositiveIntegerField(default=1, help_text='Maximum leave days a staff member can take in a single week.')),
                ('max_consecutive_days', models.PositiveIntegerField(default=7, help_text='Maximum days a single leave request may span.')),
                ('allow_backdated', models.BooleanField(default=False, help_text='Allow staff to apply for leaves starting in the past.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leave Policy',
                'verbose_name_plural': 'Leave Policies',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('casual', 'Casual Leave'), ('sick', 'Sick Leave'), ('annual', 'Annual Leave'), ('emergency', 'Emergency Leave'), ('other', 'Other')], default='casual', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=150)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='axis_saas.staff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['staff', 'status'], name='axis_saas_l_staff_i_2e5d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', 'start_date'], name='axis_saas_l_status_abc123_idx'),
        ),
    ]
