# Generated by Django 4.2.16 on 2026-09-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0024_leave_management'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='axis_saas_l_staff_i_b29c3c_idx',
            old_name='axis_saas_l_staff_i_2e5d1b_idx',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='axis_saas_l_status_01f932_idx',
            old_name='axis_saas_l_status_abc123_idx',
        ),
    ]
