# Generated by axis_patcher — LEAVE_SUSPENSION_V1
#
# Adds:
#   * LeavePolicy.count_approved_only
#   * LeavePolicy.max_rejections_before_suspension
#   * LeavePolicy.suspension_days
#   * LeaveSuspension model (FK -> Staff)

from django.db import migrations, models
import django.db.models.deletion
from datetime import date


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0025_rename_axis_saas_l_staff_i_2e5d1b_idx_axis_saas_l_staff_i_b29c3c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicy',
            name='count_approved_only',
            field=models.BooleanField(
                default=True,
                help_text=(
                    'If True, only APPROVED leaves count towards the '
                    'monthly/weekly quota. If False, PENDING leaves '
                    'count too. Rejected/Cancelled never count.'
                ),
            ),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='max_rejections_before_suspension',
            field=models.PositiveIntegerField(
                default=3,
                help_text=(
                    'Number of rejected leave requests (since the last '
                    'suspension) that automatically triggers a new '
                    'suspension. 0 disables auto-suspension.'
                ),
            ),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='suspension_days',
            field=models.PositiveIntegerField(
                default=7,
                help_text=(
                    'Length (in days) of an auto-triggered suspension. '
                    'The admin can always lift the suspension earlier.'
                ),
            ),
        ),
        migrations.CreateModel(
            name='LeaveSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('start_date', models.DateField(default=date.today)),
                ('end_date', models.DateField(blank=True, null=True, help_text='NULL = permanent until admin lifts it.')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_triggered', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('lifted_by', models.CharField(blank=True, max_length=150)),
                ('staff', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='leave_suspensions',
                    to='axis_saas.staff',
                )),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='leavesuspension',
            index=models.Index(
                fields=['staff', 'is_active'],
                name='axis_saas_l_staff_i_act_idx',
            ),
        ),
    ]
