# Generated by axis_patcher — SUBSTITUTE_FIXTURE_V1
#
# Adds the SubstituteAssignment model. One row per (class, day, period,
# date) covering a teacher who was absent on approved leave and the
# substitute teacher who took that specific period for that one day.

import datetime

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0026_leave_suspensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstituteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('period_order', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('absent_teacher', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='substitute_absences',
                    to='axis_saas.staff',
                )),
                ('school_class', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='substitute_assignments',
                    to='axis_saas.schoolclass',
                )),
                ('subject', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='substitute_assignments',
                    to='axis_saas.subject',
                )),
                ('substitute_teacher', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='substitute_assignments',
                    to='axis_saas.staff',
                )),
            ],
            options={
                'ordering': ['-date', 'day_of_week', 'period_order'],
                'unique_together': {('school_class', 'day_of_week', 'period_order', 'date')},
            },
        ),
    ]
