# Generated by axis_patcher — STAFF_BIOMETRIC_ADMIN_CONTROL_V1
#
# Adds Staff.biometric_login_enabled. When False, biometric is bypassed
# for that staff member and username+password login works normally.
# Only the school admin can toggle this from the staff profile page.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0027_substitute_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='biometric_login_enabled',
            field=models.BooleanField(
                default=True,
                help_text=(
                    "If True (default), this staff member must register and "
                    "use biometric (fingerprint / Face ID / passkey) to sign "
                    "in. If False, biometric is bypassed and the staff member "
                    "signs in with username and password only. Managed by "
                    "the school admin from the staff profile page."
                ),
            ),
        ),
    ]
