# Generated by Django 4.2.16 on 2026-09-15 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0028_staff_biometric_login_enabled'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leavesuspension',
            new_name='axis_saas_l_staff_i_7f7c6d_idx',
            old_name='axis_saas_l_staff_i_act_idx',
        ),
    ]
