# Generated by axis_patcher — LEAVE_MANAGEMENT_HARDENING_V3
#
# * Adds LeavePolicy.is_singleton (unique boolean) so the singleton
#   invariant is enforced at the DB level.
# * Adds LeavePolicy.count_working_days_only for weekday-aware quotas.
# * Dedupes any tenant that (accidentally) already has multiple
#   LeavePolicy rows before the unique constraint is added — otherwise
#   AlterField() would fail with IntegrityError and roll back the
#   whole migration, leaving the tenant stuck.
#
# Safe to re-run: the dedupe uses a guarded RunPython step.

from django.db import migrations, models


def dedupe_leave_policy(apps, schema_editor):
    """Keep the lowest-pk LeavePolicy row and delete the rest.

    Preserves the surviving row's own settings. If an operator had
    split configuration across multiple rows, they can re-apply the
    union of settings from the admin UI afterwards.
    """
    LeavePolicy = apps.get_model('axis_saas', 'LeavePolicy')
    rows = list(LeavePolicy.objects.order_by('pk'))
    if len(rows) > 1:
        keep = rows[0]
        LeavePolicy.objects.exclude(pk=keep.pk).delete()


def backfill_singleton(apps, schema_editor):
    LeavePolicy = apps.get_model('axis_saas', 'LeavePolicy')
    LeavePolicy.objects.update(is_singleton=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0029_rename_axis_saas_l_staff_i_act_idx_axis_saas_l_staff_i_7f7c6d_idx'),
    ]

    operations = [
        # 1) Drop any duplicate rows BEFORE adding the unique column,
        #    so the AlterField below cannot fail.
        migrations.RunPython(dedupe_leave_policy, noop),

        # 2) Add the new column with a nullable/unique=False shape so
        #    the backfill below can run first.
        migrations.AddField(
            model_name='leavepolicy',
            name='is_singleton',
            field=models.BooleanField(
                default=True, editable=False, unique=False,
            ),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='count_working_days_only',
            field=models.BooleanField(
                default=True,
                help_text=(
                    "If True, weekly/monthly quota counters skip the "
                    "tenant's WeeklyHoliday days. If False, calendar "
                    "days are counted."
                ),
            ),
        ),

        # 3) Backfill every surviving row to True, then tighten.
        migrations.RunPython(backfill_singleton, noop),
        migrations.AlterField(
            model_name='leavepolicy',
            name='is_singleton',
            field=models.BooleanField(
                default=True, editable=False, unique=True,
            ),
        ),
    ]
