# Generated by axis_patcher — ASSIGN_TEACHERS_HARDENING_V2
#
# Adds created_by / updated_by to PeriodTeacherAssignment so admin
# changes to the period -> teacher mapping can be audited. Existing
# rows get an empty string (the field default) because the previous
# schema did not record the actor.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0030_leave_hardening_v3'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodteacherassignment',
            name='created_by',
            field=models.CharField(
                blank=True, default='', max_length=150,
            ),
        ),
        migrations.AddField(
            model_name='periodteacherassignment',
            name='updated_by',
            field=models.CharField(
                blank=True, default='', max_length=150,
            ),
        ),
    ]
