# Generated by axis_patcher — ATTENDANCE_PRODUCTION_V2
#
#  * Period-aware StudentAttendance
#  * New models: StaffAttendance, StudentLeave,
#                AttendanceAuditLog, AttendancePolicy
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0031_period_teacher_assignment_audit'),
    ]

    operations = [
        # ---------- StudentAttendance: add v2 fields -----------------
        migrations.AddField(
            model_name='studentattendance',
            name='period_order',
            field=models.PositiveIntegerField(
                null=True, blank=True,
                help_text='NULL = full-day mark; 1..N = period slot in timetable.',
            ),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='period_timetable',
            field=models.ForeignKey(
                null=True, blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='attendance_records',
                to='axis_saas.periodstimetable',
            ),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='marked_by',
            field=models.ForeignKey(
                null=True, blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='attendance_marked_by',
                to='axis_saas.staff',
            ),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='marked_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='modified_by',
            field=models.ForeignKey(
                null=True, blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='attendance_modified_by',
                to='axis_saas.staff',
            ),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='modified_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='source',
            field=models.CharField(
                choices=[('teacher', 'Teacher'), ('admin', 'Admin'),
                         ('biometric', 'Biometric'),
                         ('auto_leave', 'Auto (Leave)'),
                         ('auto_absent', 'Auto (Absent)')],
                default='teacher', max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(
                choices=[('present', 'Present'), ('absent', 'Absent'),
                         ('late', 'Late'), ('half_day', 'Half Day'),
                         ('excused', 'Excused/Leave'), ('holiday', 'Holiday')],
                default='present', max_length=20,
            ),
        ),
        migrations.AlterModelOptions(
            name='studentattendance',
            options={'ordering': ['-date', 'student__name']},
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(
                fields=('student', 'date', 'period_order'),
                name='unique_student_date_period',
            ),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(
                condition=models.Q(period_order__isnull=True),
                fields=('student', 'date'),
                name='unique_student_date_fullday',
            ),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['student', 'date'],
                               name='axis_saas_s_student_v2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['date', 'status'],
                               name='axis_saas_s_datestatus_v2_idx'),
        ),

        # ---------- StaffAttendance ----------------------------------
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                            serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate,
                                           db_index=True)),
                ('check_in', models.DateTimeField(null=True, blank=True)),
                ('check_out', models.DateTimeField(null=True, blank=True)),
                ('status', models.CharField(
                    choices=[('present', 'Present'), ('absent', 'Absent'),
                             ('late', 'Late'), ('half_day', 'Half Day'),
                             ('on_leave', 'On Leave'), ('holiday', 'Holiday'),
                             ('weekend', 'Weekend')],
                    default='present', max_length=20)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('worked_minutes', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(
                    choices=[('biometric', 'Biometric'), ('manual', 'Manual'),
                             ('auto_leave', 'Auto (Leave)'),
                             ('holiday_auto', 'Holiday Auto'),
                             ('admin', 'Admin')],
                    default='manual', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(
                    null=True, blank=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='staff_attendance_marked',
                    to='axis_saas.staff')),
                ('staff', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='staff_attendance_records',
                    to='axis_saas.staff')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('staff', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['staff', 'date'],
                               name='axis_saas_staffatt_sd_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['date', 'status'],
                               name='axis_saas_staffatt_ds_idx'),
        ),

        # ---------- StudentLeave --------------------------------------
        migrations.CreateModel(
            name='StudentLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                            serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(
                    choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'),
                             ('family', 'Family Emergency'), ('other', 'Other')],
                    default='casual', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(
                    choices=[('pending', 'Pending'), ('approved', 'Approved'),
                             ('rejected', 'Rejected'), ('cancelled', 'Cancelled')],
                    default='pending', max_length=20)),
                ('applied_by', models.CharField(blank=True, max_length=150)),
                ('reviewed_at', models.DateTimeField(null=True, blank=True)),
                ('admin_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(
                    null=True, blank=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='reviewed_student_leaves',
                    to='axis_saas.staff')),
                ('student', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='leave_requests',
                    to='axis_saas.student')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='studentleave',
            index=models.Index(fields=['student', 'status'],
                               name='axis_saas_studleave_ss_idx'),
        ),
        migrations.AddIndex(
            model_name='studentleave',
            index=models.Index(fields=['status', 'start_date'],
                               name='axis_saas_studleave_sd_idx'),
        ),

        # ---------- AttendanceAuditLog -------------------------------
        migrations.CreateModel(
            name='AttendanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                            serialize=False, verbose_name='ID')),
                ('student_id_snapshot', models.PositiveIntegerField(null=True, blank=True)),
                ('date_snapshot', models.DateField(null=True, blank=True)),
                ('period_snapshot', models.PositiveIntegerField(null=True, blank=True)),
                ('action', models.CharField(
                    choices=[('create', 'Create'), ('update', 'Update'),
                             ('delete', 'Delete'), ('bulk_update', 'Bulk Update')],
                    max_length=20)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('changed_by_name', models.CharField(blank=True, max_length=150)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('attendance', models.ForeignKey(
                    null=True, blank=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='audit_logs',
                    to='axis_saas.studentattendance')),
                ('changed_by', models.ForeignKey(
                    null=True, blank=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='attendance_audit',
                    to='axis_saas.staff')),
            ],
            options={'ordering': ['-changed_at']},
        ),
        migrations.AddIndex(
            model_name='attendanceauditlog',
            index=models.Index(fields=['changed_at'],
                               name='axis_saas_attaudit_ca_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceauditlog',
            index=models.Index(fields=['student_id_snapshot', 'date_snapshot'],
                               name='axis_saas_attaudit_sd_idx'),
        ),

        # ---------- AttendancePolicy ----------------------------------
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                            serialize=False, verbose_name='ID')),
                ('is_singleton', models.BooleanField(default=True, editable=False,
                                                     unique=True)),
                ('attendance_mode', models.CharField(
                    choices=[('daily', 'Daily'), ('period_wise', 'Period-wise'),
                             ('both', 'Both')],
                    default='both', max_length=20)),
                ('late_threshold_minutes', models.PositiveIntegerField(default=10)),
                ('low_attendance_threshold', models.DecimalField(
                    decimal_places=2, default=75.0, max_digits=5,
                    help_text='Percentage below which a student is a low-attendance defaulter.')),
                ('auto_mark_absent_at', models.TimeField(null=True, blank=True,
                    help_text='If set, cron marks unmarked students absent at this time.')),
                ('notify_parents_on_absent', models.BooleanField(default=True)),
                ('notify_after_periods', models.PositiveIntegerField(default=2)),
                ('allow_teacher_backdate_days', models.PositiveIntegerField(default=1)),
                ('require_admin_approval', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Policy',
                'verbose_name_plural': 'Attendance Policies',
            },
        ),
    ]
