# Generated by axis_patcher — ATTENDANCE_AUTO_MARK_AND_LOCK_V1
#
# Adds the 'auto_system' value to StudentAttendance.source.choices.
# CharField.choices are validated in Python, not enforced by the DB,
# so this migration is metadata-only on a correctly-migrated database.
# It exists so `makemigrations --check` stays clean in CI.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0032_attendance_production_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='source',
            field=models.CharField(
                choices=[
                    ('teacher', 'Teacher'),
                    ('admin', 'Admin'),
                    ('biometric', 'Biometric'),
                    ('auto_leave', 'Auto (Leave)'),
                    ('auto_absent', 'Auto (Absent)'),
                    ('auto_system', 'Auto (System Present)'),
                ],
                default='teacher',
                max_length=20,
            ),
        ),
    ]
