# Generated by axis_patcher — STAFF_ATTENDANCE_OVERHAUL_V1
#
# Adds:
#   * ClassTeacherAttendancePermission (OneToOne on SchoolClass)
#   * ClassTeacherEditQuota (per class + date edit counter)
#
# These power the admin-controlled class-teacher attendance authority
# and the per-date edit lockout after N teacher edits.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0033_attendance_auto_system_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacherAttendancePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backdate_access', models.CharField(
                    choices=[
                        ('none', "None - Only today's attendance"),
                        ('read', 'Read only - View past, cannot edit'),
                        ('read_write', 'Read & Write - View and edit past'),
                    ],
                    default='none',
                    help_text=(
                        "What the class teacher can do with past "
                        "attendance. 'none' = today only; 'read' = "
                        "view-only history; 'read_write' = view and "
                        "edit history."
                    ),
                    max_length=20,
                )),
                ('max_edits_per_date', models.PositiveIntegerField(
                    default=1,
                    help_text=(
                        "Maximum number of times the class teacher can "
                        "edit a single date's attendance before it "
                        "permanently locks for the class teacher."
                    ),
                )),
                ('view_history_days', models.PositiveIntegerField(
                    default=30,
                    help_text=(
                        "How many days back the class teacher can view "
                        "the attendance records for this class."
                    ),
                )),
                ('edit_history_days', models.PositiveIntegerField(
                    default=5,
                    help_text=(
                        "How many days back the class teacher can edit "
                        "the attendance records for this class."
                    ),
                )),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
                ('school_class', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='attendance_permission',
                    to='axis_saas.schoolclass',
                )),
            ],
            options={
                'verbose_name': 'Class Teacher Attendance Permission',
                'verbose_name_plural': 'Class Teacher Attendance Permissions',
            },
        ),
        migrations.CreateModel(
            name='ClassTeacherEditQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('teacher_edit_count', models.PositiveIntegerField(default=0)),
                ('last_teacher_edit_at', models.DateTimeField(blank=True, null=True)),
                ('last_teacher_edit_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('last_teacher_edit_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('school_class', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='attendance_edit_quotas',
                    to='axis_saas.schoolclass',
                )),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='classteachereditquota',
            index=models.Index(
                fields=['school_class', 'date'],
                name='axis_saas_ct_quota_sd_idx',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='classteachereditquota',
            unique_together={('school_class', 'date')},
        ),
    ]
