# Generated by Django 4.2.16 on 2026-09-16 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0034_class_teacher_attendance_permissions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendanceauditlog',
            new_name='axis_saas_a_changed_c271c5_idx',
            old_name='axis_saas_attaudit_ca_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceauditlog',
            new_name='axis_saas_a_student_efb311_idx',
            old_name='axis_saas_attaudit_sd_idx',
        ),
        migrations.RenameIndex(
            model_name='classteachereditquota',
            new_name='axis_saas_c_school__44a5db_idx',
            old_name='axis_saas_ct_quota_sd_idx',
        ),
        migrations.RenameIndex(
            model_name='staffattendance',
            new_name='axis_saas_s_staff_i_478858_idx',
            old_name='axis_saas_staffatt_sd_idx',
        ),
        migrations.RenameIndex(
            model_name='staffattendance',
            new_name='axis_saas_s_date_d1b94f_idx',
            old_name='axis_saas_staffatt_ds_idx',
        ),
        migrations.RenameIndex(
            model_name='studentattendance',
            new_name='axis_saas_s_student_a1cc39_idx',
            old_name='axis_saas_s_student_v2_idx',
        ),
        migrations.RenameIndex(
            model_name='studentattendance',
            new_name='axis_saas_s_date_d63b57_idx',
            old_name='axis_saas_s_datestatus_v2_idx',
        ),
        migrations.RenameIndex(
            model_name='studentleave',
            new_name='axis_saas_s_student_8693f4_idx',
            old_name='axis_saas_studleave_ss_idx',
        ),
        migrations.RenameIndex(
            model_name='studentleave',
            new_name='axis_saas_s_status_c5ccb4_idx',
            old_name='axis_saas_studleave_sd_idx',
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='substituteassignment',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
