# Generated by axis_patcher — ASSIGN_MULTI_TIMETABLE_V1
#
# Lets a single SchoolClass have MULTIPLE PeriodsTimetable assignments.
#
#   * ClassTimetableAssignment.school_class changes from OneToOneField
#     (one-per-class) to ForeignKey (many-per-class).
#   * A new UniqueConstraint (school_class, timetable) prevents the
#     exact same timetable from being assigned to the same class twice.
#
# The "all assigned timetables must share the same ScheduleLabel" rule
# is enforced in the view layer (views/timetable_assignments.py) — it
# cannot be expressed as a single-column DB constraint.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0035_rename_axis_saas_attaudit_ca_idx_axis_saas_a_changed_c271c5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtimetableassignment',
            name='school_class',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='timetable_assignments',
                to='axis_saas.schoolclass',
            ),
        ),
        migrations.AddConstraint(
            model_name='classtimetableassignment',
            constraint=models.UniqueConstraint(
                fields=['school_class', 'timetable'],
                name='unique_class_timetable_assignment',
            ),
        ),
    ]
